### PR TITLE
Adding Pipeline support

### PR DESCRIPTION
**Pull request by abishek3876**
This is a rework of #16 with only the minimally required changes.

This PR adds the Pipeline support for the plugin. Now, users can provide commands like the following in their pipeline script:
`perfpublisher healthy: '0', metrics: 'time=time', name: '*.xml', threshold: '0', unhealthy: '0'`

Again, thanks to @aletu, for his work on this.

### CODE REVIEW

**Comment by eschava** [comment]
Have you tried "mvn package" command?

**Comment by abishek3876** [comment]
Oopsie... failures... I will fix them and push asap...

**Comment by abishek3876** [comment]
@eschava I have fixed the error. Javadoc generation was failing for me always, so had to use "-Dmaven.javadoc.skip=true" and the package command works fine now. PTAL.

**Comment by eschava** [comment]
I've put updated plugin to my Jenkins and see that HTML output is escaped now
E.g. "Build Report" page has header like
<div class="progress-container"><div id="red" style="width:15%;">8</div><div id="blue" style="width:85%;">232</div></div>

**Comment by abishek3876** [comment]
@eschava , Is it having those headers with my latest commits. I found those headers after adding the escape-by-default tag to the jelly files. I have since reverted those changes and instead ignored the jelly PI check for now. So this shouldn't be happening with the latest change if I am not wrong.

**Comment by eschava** [comment]
I still have

> [ERROR] hudson\plugins\PerfPublisher\CategoryDetails\index.jelly(org.jvnet.hudson.test.JellyTestSuiteBuilder$JellyCheck)  Time elapsed: 0.219 s  <<< FAILURE!
> java.lang.AssertionError: <?jelly escape-by-default='true'?> is missing in file:/C:/Users/Eugeny.Schava/Downloads/perfpublisher-plugin/target/classes/hudson/plugins/PerfPublisher/CategoryDetails/index.jelly

error during mvn package command

**Comment by abishek3876** [comment]
That's strange. I am able to execute the command just fine. Can you escape the error and paste it... I guess part of the information is missing in your comment. Also, the Jelly check test shouldn't run at all since I have disabled it by default in my last commit.

**Comment by eschava** [comment]
Sorry, mvn clean helped. Checking new build on my Jenkins box

**Comment by eschava** [comment]
Applied and released new 8.05 version

**Pull request merged**
