### PR TITLE
Update PerfPublisherBuildAction.java

### PR DESCRIPTION
**Pull request by dazze1812**
Possible solution for #11

### CODE REVIEW

**Comment by eschava** [comment]
I'm OK to merge the fix but why did you replace 
failedTests > healthDescriptor.getUnstableHealth() with 
failedTests >= healthDescriptor.getUnstableHealth() ?

**Comment by dazze1812** [comment]
Currently it is not possible to set the build to unstable when exactly one test failed. In our typical use cases we want a notification if not all of the tests passed.

**Comment by eschava** [comment]
I understand your point but this solution looks not backward compatible
I think it would be better support 0 as correct value.

**Comment by dazze1812** [comment]
This is right. But this would also break the backward compatibility for those who set 0 to leave the build status untouched.
I can live with both solutions.

**Comment by eschava** [comment]
Reworked a bit

**Pull request closed without merging**
